# Generated by Django 4.2.20 on 2025-04-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pic',
            field=models.ImageField(default='no_picture.png', upload_to='customers'),
        ),
    ]
